import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navegation/Navbar";
import { ButtonNavbar, navbarLinks } from "@/variables/navbarInfo";
import Footer from "@/components/Navegation/Footer";
import { footerInfos } from "@/variables/footerInfos";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar linksNav={navbarLinks} buttonNav={ButtonNavbar} />
        <div className="min-h-screen">{children}</div>
        <Footer
          contactInfo={footerInfos.contactInfo}
          company={footerInfos.company}
          creator={footerInfos.creator}
          pages={footerInfos.pages}
        />
      </body>
    </html>
  );
}
